package:
  name: pymzml
  version: "2.5.0"

source:
  url: https://files.pythonhosted.org/packages/85/d5/bd447807243a61b9c739da41566fa9a526c79f06902192c30cb3b4b6c724/pymzml-2.5.0.macosx-10.15-x86_64.tar.gz
  sha256: 0425e8fe2ecd790823f7432557cd0b69fc17ae490c128b3b47d2844c2d28065d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python >3
    - pip
  run:
    - python >3
    - numpy
    - plotly
    - regex

test:
  imports:
    - pymzml

about:
  home: http://pymzml.github.com
  license: GNU General Public License (GPL)
  license_file: LICENSE.txt
  summary: 'high-throughput mzML parsing'
  license_family: LGPL

extra:
  identifiers:
    - biotools:pymzml
