{% set name = "protgraph" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7b0cb2532e06bc7aa8a194c02f317ed32b1cbdfeec1d6788d105b551d3a12bab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protgraph=protgraph.protgraph:main

requirements:
  host:
    - biopython
    - mysql-connector-python
    - networkx
    - pip
    - python >=3.6
    - tqdm
    - aenum
    - isodate
    - wcwidth
    - importlib_metadata
    - redis-py
    - prettytable
    - python-igraph
    - texttable
    - gremlinpython
    - redisgraph-py

  run:
    - biopython
    - mysql-connector-python
    - networkx
    - psycopg >=3
    - cassandra-driver
    - python >=3.6
    - tqdm
    - aenum
    - isodate
    - wcwidth
    - importlib_metadata
    - redis-py
    - prettytable
    - python-igraph
    - texttable
    - gremlinpython
    - redisgraph-py

test:
  imports:
    - protgraph
    - protgraph.export
    - protgraph.export.peptides
    - protgraph.ft_execution
  commands:
    - protgraph --help

about:
  home: "https://github.com/mpc-bioinformatics/ProtGraph"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "ProtGraph, a graph generator for proteins."

extra:
  recipe-maintainers:
    - Luxxii
