package:
  name: bcbiogff
  version: 0.6.7

source:
  url: https://files.pythonhosted.org/packages/36/ea/43b0b78123aa89b352c401339be0a560c46f3d11b42ad3156a927761037d/bcbio-gff-0.6.7.tar.gz
  sha256: 6e6f70639149612272a3b298a93ac50bba6f9ecece934f2a0ea86d4abde975da

build:
  noarch: python
  number: 0

requirements:
  host:
  - python
  - six
  run:
  - python
  - six
  - biopython

test:
  imports:
    - BCBio.GFF

about:
  home: https://github.com/chapmanb/bcbb/blob/master/gff
  license: Biopython License Agreement
  summary: Read and write Generic Feature Format (GFF) with Biopython integration.
