{% set name = "pftools" %}
{% set version = "3.2.10" %}
{% set sha256 = "a0376f67531655985d7f52468d4f2a491c122c799ac8bfed486990cb0c1f6171" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/sib-swiss/pftools3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - r-base
    - perl
    - zlib
    - perl-file-slurp

  run:
    - r-base
    - perl
    - zlib
    - perl-file-slurp

test:
  commands:
    - gtop -h 2>&1 | grep -i usage
    - pfmake -h 2>&1 | grep -i usage
    - pfscan -h 2>&1 | grep -i usage
    - pfscanV3 -h 2>&1 | grep -i usage
    - pfw -h 2>&1 | grep -i usage
    - ptoh -h 2>&1 | grep -i usage
    - htop -h 2>&1 | grep -i usage
    - pfscale -h 2>&1 | grep -i usage
    - pfsearch -h 2>&1 | grep -i usage
    - pfsearchV3 -h 2>&1 | grep -i usage
    - psa2msa -h 2>&1 | grep -i usage
    - 2ft -h 2>&1 | grep -i usage
    - 6ft -h 2>&1 | grep -i usage
    - ptof -h 2>&1 | grep -i usage

about:
  home: https://web.expasy.org/pftools/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: 'A generalized profile syntax for biomolecular sequence motifs and its function in automatic sequence interpretation.'
  dev_url: https://github.com/sib-swiss/pftools3
